ARG VERSION=14

FROM bitnami/postgresql-repmgr:${VERSION} AS builder

# postgres
FROM sdrzlyz/pg:${VERSION}

COPY --from=builder /opt/bitnami /opt/bitnami

RUN rm -rf /docker-entrypoint-initdb.d/*
RUN /opt/bitnami/scripts/postgresql-repmgr/postunpack.sh
RUN /opt/bitnami/scripts/locales/add-extra-locales.sh
ENV APP_VERSION="13.10.0" \
    BITNAMI_APP_NAME="postgresql-repmgr" \
    LANG="en_US.UTF-8" \
    LANGUAGE="en_US:en" \
    NSS_WRAPPER_LIB="/opt/bitnami/common/lib/libnss_wrapper.so"

ENTRYPOINT [ "/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh" ]
CMD [ "/opt/bitnami/scripts/postgresql-repmgr/run.sh" ]
