ARG VERSION=16

# Build tools for timescaledb
ARG GO_VERSION=1.19.6
FROM golang:${GO_VERSION}-alpine AS tools

ENV TOOLS_VERSION 0.8.1

# https://github.com/timescale/timescaledb-docker/blob/main/Dockerfile
RUN apk update && apk add --no-cache git gcc \
    && go install github.com/timescale/timescaledb-tune/cmd/timescaledb-tune@latest \
    && go install github.com/timescale/timescaledb-parallel-copy/cmd/timescaledb-parallel-copy@latest

# postgres
FROM postgres:${VERSION}-bullseye

ARG CITUS=12.1.0
ARG POSTGRESQL_HLL=2.18
ARG POSTGRESQL_TOPN=2.6.0
ARG POSTGIS=3.4.0+dfsg-1.pgdg110+1
ARG PGROUTING=3.5.1
ARG TIMESCALE=2.12.0
ARG ZOMBODB=3000.1.25
ARG PGVECTOR=0.5.0
ARG PG_HINT_PLAN=16_1_6_0
ARG PG_CRON=1.6.0
ARG PG_IVM=1.7
ARG ORAFCE=4_6_1
ARG PGSQL_HTTP=1.6.0
ARG PGAUDIT=16.0
ARG REPMGR=5.4.1

# set timezone
ENV TZ PRC

COPY _curl.sh /usr/local/bin/

RUN _curl.sh https://packages.groonga.org/debian/groonga-apt-source-latest-bullseye.deb > /tmp/groonga.deb \
    && apt-get install -y /tmp/groonga.deb \
    && apt-get update && apt-get install -y --no-install-recommends sudo \
    && echo "postgres ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER postgres

# dep:
## pgrouting: libboost-graph-dev
## timescale: libkrb5-dev
## age: build-essential libreadline-dev zlib1g-dev flex bison
## zombodb: bison flex zlib1g zlib1g-dev pkg-config make libssl-dev libreadline-dev
## pgsql-http: libcurl4-openssl-dev
## repmgr: flex libedit-dev libkrb5-dev libpam0g-dev libreadline-dev libselinux1-dev libssl-dev libxml2-dev libxslt1-dev
## repmgr-pg15: liblz4-dev libzstd-dev

RUN sudo apt-get install -y --no-install-recommends \
        ca-certificates \
        procps \
        curl \
        build-essential \
        git \
        dpkg-dev \
        gcc \
        libc-dev \
        make \
        cmake \
        wget \
        pkg-config \
        postgresql-server-dev-$PG_MAJOR \
        # pgrouting
        libboost-graph-dev \
        # timescale, repmgr
        libkrb5-dev \
        # age, zombodb
        bison flex zlib1g-dev libreadline-dev \
        # zombodb
        zlib1g libssl-dev \
        # pgsql-http
        libcurl4-openssl-dev \
        # repmgr
        liblz4-dev libzstd-dev libedit-dev libpam0g-dev libselinux1-dev libxml2-dev libxslt1-dev libjson-c-dev \
# citus https://github.com/citusdata/citus https://github.com/citusdata/docker/blob/master/Dockerfile
    && curl -s https://install.citusdata.com/community/deb.sh | sudo bash \
    && sudo apt-get install -y --no-install-recommends \
                        postgresql-$PG_MAJOR-citus-12.1=$CITUS.citus-1 \
# pglogical https://github.com/2ndQuadrant/pglogical
                        postgresql-$PG_MAJOR-pglogical \
# postgis https://github.com/postgis/postgis/tags https://github.com/postgis/docker-postgis/blob/master/16-3.4/Dockerfile
                        postgresql-$PG_MAJOR-postgis-3=$POSTGIS \
                        postgresql-$PG_MAJOR-postgis-3-scripts \
# pgroonga https://github.com/pgroonga/pgroonga
                        postgresql-$PG_MAJOR-pgdg-pgroonga \
# pg_auto_failover https://github.com/hapostgres/pg_auto_failover
                        pg-auto-failover-cli \
                        postgresql-$PG_MAJOR-auto-failover \
# hll https://github.com/citusdata/postgresql-hll/tags
    && wget -O /tmp/hll.tar.gz "https://github.com/citusdata/postgresql-hll/archive/refs/tags/v${POSTGRESQL_HLL}.tar.gz" \
    && mkdir -p /tmp/hll \
    && tar --extract --file /tmp/hll.tar.gz --directory /tmp/hll --strip-components 1 \
        && cd /tmp/hll \
        && make -j$(nproc) && sudo make install \
# topn https://github.com/citusdata/postgresql-topn/tags
    && wget -O /tmp/topn.tar.gz "https://github.com/citusdata/postgresql-topn/archive/refs/tags/v${POSTGRESQL_TOPN}.tar.gz" \
    && mkdir -p /tmp/topn \
    && tar --extract --file /tmp/topn.tar.gz --directory /tmp/topn --strip-components 1 \
        && cd /tmp/topn \
        && make -j$(nproc) && sudo make install \
# pgrouting https://github.com/pgRouting/pgrouting https://github.com/pgRouting/docker-pgrouting
    && wget -O /tmp/pgrouting.tar.gz "https://github.com/pgRouting/pgrouting/archive/v${PGROUTING}.tar.gz" \
        && mkdir -p /tmp/pgrouting/build \
        && tar --extract --file /tmp/pgrouting.tar.gz --directory /tmp/pgrouting --strip-components 1 \
        && cd /tmp/pgrouting/build \
        && cmake .. \
        && make -j$(nproc) && sudo make install \
# timescale https://github.com/timescale/timescaledb https://github.com/timescale/timescaledb-docker
    && git clone -b ${TIMESCALE} https://github.com/timescale/timescaledb /tmp/timescale \
        && cd /tmp/timescale \
        && ./bootstrap -DCMAKE_BUILD_TYPE=RelWithDebInfo -DREGRESS_CHECKS=OFF -DTAP_CHECKS=OFF -DGENERATE_DOWNGRADE_SCRIPT=ON -DWARNINGS_AS_ERRORS=OFF -DPROJECT_INSTALL_METHOD="docker" \
        && cd build && make -j$(nproc) && sudo make install \
# # age https://github.com/apache/age https://age.apache.org/age-manual/master/intro/setup.html
#     && git clone -b PG${PG_MAJOR} https://github.com/apache/age /tmp/age \
#         && cd /tmp/age \
#         && make && sudo make install \
# zombodb https://github.com/zombodb/zombodb
    && export CARGO_HOME=/tmp/cargo && export RUSTUP_HOME=/tmp/rustup && export PATH=$CARGO_HOME/bin:$PATH \
        && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y \
        && git clone -b v${ZOMBODB} https://github.com/zombodb/zombodb /tmp/zombodb \
        && cd /tmp/zombodb \
        && cargo install -j$(nproc) cargo-pgrx --version $(cat Cargo.toml | grep "pgrx = " | sed 's/pgrx = //g' | sed 's/"//g') \
        && cargo pgrx init --pg${PG_MAJOR}=$(which pg_config) \
        && sudo bash -c 'CARGO_HOME=/tmp/cargo RUSTUP_HOME=/tmp/rustup PATH=$CARGO_HOME/bin:$PATH PGRX_HOME=/var/lib/postgresql/.pgrx cargo pgrx install --release' \
# vector https://github.com/pgvector/pgvector/tags
    && git clone -b v${PGVECTOR} https://github.com/pgvector/pgvector.git /tmp/pgvector \
        && cd /tmp/pgvector \
        && make && sudo make install \
# pg_hint_plan https://github.com/ossc-db/pg_hint_plan
    && wget -O /tmp/pg_hint_plan.tar.gz "https://github.com/ossc-db/pg_hint_plan/archive/REL${PG_HINT_PLAN}.tar.gz" \
        && mkdir -p /tmp/pg_hint_plan \
        && tar --extract --file /tmp/pg_hint_plan.tar.gz --directory /tmp/pg_hint_plan --strip-components 1 \
        && cd /tmp/pg_hint_plan \
        && make && sudo make install \
# pg_cron https://github.com/citusdata/pg_cron
    && wget -O /tmp/pg_cron.tar.gz "https://github.com/citusdata/pg_cron/archive/v${PG_CRON}.tar.gz" \
        && mkdir -p /tmp/pg_cron \
        && tar -zxf /tmp/pg_cron.tar.gz -C /tmp/pg_cron --strip-components 1 \
        && cd /tmp/pg_cron \
        && make && sudo make install \
# pg_ivm https://github.com/sraoss/pg_ivm
    && wget -O /tmp/pg_ivm.tar.gz "https://github.com/sraoss/pg_ivm/archive/v${PG_IVM}.tar.gz" \
        && mkdir -p /tmp/pg_ivm \
        && tar -zxf /tmp/pg_ivm.tar.gz -C /tmp/pg_ivm --strip-components 1 \
        && cd /tmp/pg_ivm \
        && make && sudo make install \
# orafce https://github.com/orafce/orafce
    && wget -O /tmp/orafce.tar.gz "https://github.com/orafce/orafce/archive/VERSION_${ORAFCE}.tar.gz" \
        && mkdir -p /tmp/orafce \
        && tar --extract --file /tmp/orafce.tar.gz --directory /tmp/orafce --strip-components 1 \
        && cd /tmp/orafce \
        && make && sudo make install \
# http https://github.com/pramsey/pgsql-http
    && wget -O /tmp/pgsql-http.tar.gz "https://github.com/pramsey/pgsql-http/archive/v${PGSQL_HTTP}.tar.gz" \
        && mkdir -p /tmp/pgsql-http \
        && tar --extract --file /tmp/pgsql-http.tar.gz --directory /tmp/pgsql-http --strip-components 1 \
        && cd /tmp/pgsql-http \
        && make && sudo make install \
# pgaudit https://github.com/pgaudit/pgaudit/tags
    && wget -O /tmp/pgaudit.tar.gz "https://github.com/pgaudit/pgaudit/archive/${PGAUDIT}.tar.gz" \
        && mkdir -p /tmp/pgaudit \
        && tar --extract --file /tmp/pgaudit.tar.gz --directory /tmp/pgaudit --strip-components 1 \
        && cd /tmp/pgaudit \
        && sudo make install USE_PGXS=1 \
# pg_jieba https://github.com/jaiminpan/pg_jieba
    && git clone https://github.com/jaiminpan/pg_jieba /tmp/pg_jieba \
        && cd /tmp/pg_jieba \
        && git submodule update --init --recursive \
        && mkdir build && cd build \
        && cmake -DCMAKE_PREFIX_PATH=/usr/share/postgresql/$PG_MAJOR -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/$PG_MAJOR/server .. \
        && make && sudo make install \
# wal2json WAL https://github.com/eulerto/wal2json
    && git clone https://github.com/eulerto/wal2json /tmp/wal2json \
        && cd /tmp/wal2json \
        && make && sudo make install \
# decoder_raw WAL https://github.com/michaelpq/pg_plugins
    && git clone https://github.com/michaelpq/pg_plugins /tmp/pg_plugins \
        && cd /tmp/pg_plugins/decoder_raw \
        && make && sudo make install \
# repmgr https://github.com/EnterpriseDB/repmgr
    && wget -O /tmp/repmgr.tar.gz "https://github.com/EnterpriseDB/repmgr/archive/v${REPMGR}.tar.gz" \
    && mkdir -p /tmp/repmgr \
    && tar --extract --file /tmp/repmgr.tar.gz --directory /tmp/repmgr --strip-components 1 \
        && cd /tmp/repmgr \
        && ./configure && make && sudo make install \
# locale
    && sudo bash -c 'echo -e "en_US.UTF-8 UTF-8\nzh_CN.UTF-8 UTF-8" >> /etc/locale.gen' && sudo locale-gen \
# clean
    && sudo apt-get autoremove --purge -y --allow-remove-essential \
        curl \
        build-essential \
        git \
        dpkg-dev \
        gcc \
        libc-dev \
        make \
        cmake \
        wget \
        pkg-config \
        postgresql-server-dev-$PG_MAJOR \
        libboost-graph-dev \
        libkrb5-dev \
        bison flex zlib1g-dev libreadline-dev \
        libssl-dev \
        libcurl4-openssl-dev \
        liblz4-dev libzstd-dev libedit-dev libpam0g-dev libselinux1-dev libxml2-dev libxslt1-dev libjson-c-dev \
    && sudo apt-get clean -y \
    && sudo rm -rf \
        "${HOME}/.cache" \
        /var/lib/apt/lists/* \
        /tmp/* \
        /var/tmp/* \
        /var/lib/postgresql/.profile \
        /var/lib/postgresql/.pgrx

USER root

# multi: using comma as spliter, example: shared_preload_libraries='citus,timescaledb'
RUN echo "shared_preload_libraries='citus,pg_stat_statements,pgautofailover,pgaudit,timescaledb,pg_cron,pglogical'" >> /usr/share/postgresql/postgresql.conf.sample

# select name,setting from pg_settings where name like 'pgaudit%';
# all but except misc
#pgaudit.log = 'all, -misc'
#pgaudit.log_client = on
#pgaudit.log_parameter = on
#pgaudit.log_relation = on
#pgaudit.log_statement_once = on

# add scripts to run after initdb
COPY extension/ /docker-entrypoint-initdb.d/

# add tools
COPY --from=tools /go/bin/* /usr/local/bin/

# add health check script
COPY pg_healthcheck wait-for-manager.sh /
RUN chmod +x /wait-for-manager.sh

# entry point unsets PGPASSWORD, but we need it to connect to workers
# https://github.com/docker-library/postgres/blob/33bccfcaddd0679f55ee1028c012d26cd196537d/12/docker-entrypoint.sh#L303
RUN sed "/unset PGPASSWORD/d" -i /usr/local/bin/docker-entrypoint.sh

# config tuning
# replace last docker_temp_server_stop with sed to change pg.max_connections and cron.timezone 
# \o047 for single quote
RUN sed -i ':a;N;$!ba;s#\(.*\)docker_temp_server_stop#\1docker_temp_server_stop\n                        sed -i "s/max_connections = 100/max_connections = 1000/" /var/lib/postgresql/data/postgresql.conf\n                        echo "cron.timezone = \o047PRC\o047" >> /var/lib/postgresql/data/postgresql.conf#' /usr/local/bin/docker-entrypoint.sh

ENV TIMESCALEDB_TELEMETRY off

HEALTHCHECK --interval=4s --timeout=10s --retries=3 --start-period=6s CMD ./pg_healthcheck
