FROM sdrzlyz/ffmpeg:alpine as builder

FROM sdrzlyz/nginx:1.22.1

COPY --from=builder /build /
COPY bin/ttyd /usr/local/bin/ttyd

ENV LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib:/usr/lib:/lib

RUN chmod +x /usr/local/bin/ttyd
