FROM sdrzlyz/ffmpeg:alpine-static as builder

FROM sdrzlyz/nginx:1.26.3

COPY --from=builder /ffmpeg /ffprobe /usr/local/bin/
COPY bin/ttyd /usr/local/bin/ttyd

# ENV LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/lib:/usr/lib:/lib

RUN chmod +x /usr/local/bin/ttyd
