FROM centos:7

ARG VERSION=1.16.1

COPY ./dep.sh /opt/dep.sh

RUN chmod +x /opt/dep.sh && \
    /opt/dep.sh

COPY ./nginx-1.6.sh /opt/nginx.sh

RUN chmod +x /opt/nginx.sh && /opt/nginx.sh ${VERSION}

EXPOSE 80 443 443/udp

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
