FROM centos:7

ARG VERSION=1.20.2

COPY quic-dep.sh quic-nginx.sh /opt/

RUN chmod +x /opt/{quic-dep.sh,quic-nginx.sh} && /opt/quic-dep.sh && /opt/quic-nginx.sh

COPY ssl/* /etc/nginx/

COPY cors.conf /etc/nginx

EXPOSE 80 443 443/UDP

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
