# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Infra

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "true"

      # https://github.com/docker/login-action
      - name: Log into docker hub
        uses: docker/login-action@v1
        with:
          username: sdrzlyz
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build infra image
        run: |
          bash ./build.sh envoy
          bash ./build.sh ffmpeg
          bash ./build.sh ffmpeg 4
          bash ./build.sh go-dev
          bash ./build.sh ikev2
          bash ./build.sh m7s
          bash ./build.sh nginx
          bash ./build.sh nginx ffmpeg
          bash ./build.sh nginx quic
          bash ./build.sh pg
          bash ./build.sh pg 14
          bash ./build.sh redis
          bash ./build.sh tools
