# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Infra Envoy

on: workflow_dispatch

jobs:
  build-envoy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "true"

      # https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sdrzlyz
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build envoy bin
        run: |
          bash ./envoy/build_envoy.sh
