# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Infra FFmpeg

on: workflow_dispatch

jobs:
  build-alpine-static:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      # https://github.com/docker/login-action
      - name: Log into docker hub
        uses: docker/login-action@v2
        with:
          username: sdrzlyz
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build ffmpeg image
        run: |
          bash ./build.sh ffmpeg alpine-static
  # build-centos:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         submodules: "true"

  #     # https://github.com/docker/login-action
  #     - name: Log into docker hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: sdrzlyz
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build ffmpeg image
  #       run: |
  #         bash ./build.sh ffmpeg
  #         bash ./build.sh ffmpeg 4
